/**
 * PDF report generator for terminal modules.
 *
 * Uses jsPDF + jspdf-autotable for tables and html2canvas for chart capture.
 * Styled to match the terminal's dark aesthetic with amber accents.
 */
import jsPDF from "jspdf";
import autoTable, { type RowInput } from "jspdf-autotable";
import html2canvas from "html2canvas";

const COLORS = {
  bg: [18, 18, 22] as [number, number, number],
  panel: [26, 26, 32] as [number, number, number],
  border: [50, 50, 58] as [number, number, number],
  text: [220, 220, 225] as [number, number, number],
  textDim: [148, 148, 158] as [number, number, number],
  amber: [255, 140, 0] as [number, number, number],
  up: [46, 204, 113] as [number, number, number],
  down: [255, 59, 59] as [number, number, number],
  blue: [59, 157, 255] as [number, number, number],
  white: [255, 255, 255] as [number, number, number],
};

export interface ReportConfig {
  title: string;
  code: string;
  subtitle?: string;
  source: string;
  asOf?: string;
}

export class PdfReport {
  private doc: jsPDF;
  private y: number;
  private pageWidth: number;
  private margin: number;
  private contentWidth: number;

  constructor(config: ReportConfig) {
    this.doc = new jsPDF({ orientation: "landscape", unit: "pt", format: "a4" });
    this.margin = 36;
    this.pageWidth = this.doc.internal.pageSize.getWidth();
    this.contentWidth = this.pageWidth - this.margin * 2;
    this.y = this.margin;

    this.drawBackground();
    this.drawHeader(config);
  }

  private drawBackground() {
    this.doc.setFillColor(...COLORS.bg);
    this.doc.rect(0, 0, this.doc.internal.pageSize.getWidth(), this.doc.internal.pageSize.getHeight(), "F");
  }

  private drawHeader(config: ReportConfig) {
    this.doc.setFillColor(...COLORS.panel);
    this.doc.rect(0, 0, this.pageWidth, 64, "F");
    this.doc.setDrawColor(...COLORS.border);
    this.doc.line(0, 64, this.pageWidth, 64);

    this.doc.setFont("helvetica", "bold");
    this.doc.setFontSize(8);
    this.doc.setTextColor(...COLORS.amber);
    this.doc.text(config.code, this.margin, 24);

    this.doc.setFontSize(16);
    this.doc.setTextColor(...COLORS.white);
    this.doc.text(config.title, this.margin + 48, 26);

    if (config.subtitle) {
      this.doc.setFont("helvetica", "normal");
      this.doc.setFontSize(9);
      this.doc.setTextColor(...COLORS.textDim);
      this.doc.text(config.subtitle, this.margin, 44);
    }

    this.doc.setFont("helvetica", "normal");
    this.doc.setFontSize(7);
    this.doc.setTextColor(...COLORS.textDim);
    const rightText = `Source: ${config.source}  |  ${config.asOf ?? new Date().toISOString().slice(0, 10)}`;
    this.doc.text(rightText, this.pageWidth - this.margin, 26, { align: "right" });

    this.doc.setFontSize(6);
    this.doc.text("Generated by Market Terminal", this.pageWidth - this.margin, 44, { align: "right" });

    this.y = 80;
  }

  checkPage(needed = 80) {
    const pageHeight = this.doc.internal.pageSize.getHeight();
    if (this.y + needed > pageHeight - this.margin) {
      this.doc.addPage();
      this.drawBackground();
      this.y = this.margin;
    }
  }

  sectionTitle(title: string, tag?: { text: string; color?: [number, number, number] }) {
    this.checkPage(40);
    this.doc.setFillColor(...COLORS.panel);
    this.doc.roundedRect(this.margin, this.y, this.contentWidth, 22, 2, 2, "F");
    this.doc.setDrawColor(...COLORS.border);
    this.doc.roundedRect(this.margin, this.y, this.contentWidth, 22, 2, 2, "S");

    this.doc.setFont("helvetica", "bold");
    this.doc.setFontSize(9);
    this.doc.setTextColor(...COLORS.amber);
    this.doc.text(title, this.margin + 8, this.y + 14);

    if (tag) {
      const tagColor = tag.color ?? COLORS.textDim;
      this.doc.setFont("helvetica", "normal");
      this.doc.setFontSize(7);
      this.doc.setTextColor(...tagColor);
      this.doc.text(tag.text, this.pageWidth - this.margin - 8, this.y + 14, { align: "right" });
    }

    this.y += 30;
  }

  kpiStrip(kpis: { label: string; value: string; sub?: string; tone?: "up" | "down" | "amber" | "neutral" }[]) {
    this.checkPage(50);
    const cellWidth = this.contentWidth / kpis.length;

    this.doc.setFillColor(...COLORS.panel);
    this.doc.roundedRect(this.margin, this.y, this.contentWidth, 42, 2, 2, "F");
    this.doc.setDrawColor(...COLORS.border);
    this.doc.roundedRect(this.margin, this.y, this.contentWidth, 42, 2, 2, "S");

    kpis.forEach((kpi, i) => {
      const x = this.margin + i * cellWidth + cellWidth / 2;

      this.doc.setFont("helvetica", "normal");
      this.doc.setFontSize(6);
      this.doc.setTextColor(...COLORS.textDim);
      this.doc.text(kpi.label, x, this.y + 12, { align: "center" });

      const valueColor = kpi.tone === "up" ? COLORS.up : kpi.tone === "down" ? COLORS.down : kpi.tone === "amber" ? COLORS.amber : COLORS.white;
      this.doc.setFont("helvetica", "bold");
      this.doc.setFontSize(11);
      this.doc.setTextColor(...valueColor);
      this.doc.text(kpi.value, x, this.y + 27, { align: "center" });

      if (kpi.sub) {
        this.doc.setFont("helvetica", "normal");
        this.doc.setFontSize(6);
        this.doc.setTextColor(...COLORS.textDim);
        this.doc.text(kpi.sub, x, this.y + 37, { align: "center" });
      }

      if (i < kpis.length - 1) {
        this.doc.setDrawColor(...COLORS.border);
        this.doc.line(this.margin + (i + 1) * cellWidth, this.y + 6, this.margin + (i + 1) * cellWidth, this.y + 36);
      }
    });

    this.y += 52;
  }

  table(
    headers: string[],
    rows: RowInput[],
    opts?: { columnStyles?: Record<number, { halign?: "left" | "center" | "right"; cellWidth?: number }> }
  ) {
    this.checkPage(60);

    autoTable(this.doc, {
      startY: this.y,
      margin: { left: this.margin, right: this.margin },
      head: [headers],
      body: rows,
      theme: "plain",
      styles: {
        fillColor: COLORS.bg,
        textColor: COLORS.text,
        lineColor: COLORS.border,
        lineWidth: 0.5,
        fontSize: 7,
        cellPadding: { top: 4, bottom: 4, left: 6, right: 6 },
        font: "helvetica",
      },
      headStyles: {
        fillColor: COLORS.panel,
        textColor: COLORS.amber,
        fontStyle: "bold",
        fontSize: 7,
      },
      alternateRowStyles: {
        fillColor: [22, 22, 28] as [number, number, number],
      },
      columnStyles: opts?.columnStyles ?? {},
    });

    this.y = ((this.doc as any).lastAutoTable?.finalY ?? this.y + 28) + 12;
  }

  metricRows(metrics: { label: string; value: string; tone?: "up" | "down" | "neutral" }[]) {
    this.checkPage(metrics.length * 16 + 10);

    metrics.forEach((m) => {
      this.doc.setFillColor(this.y % 2 === 0 ? COLORS.bg[0] : 22, this.y % 2 === 0 ? COLORS.bg[1] : 22, this.y % 2 === 0 ? COLORS.bg[2] : 28);
      this.doc.rect(this.margin, this.y, this.contentWidth, 16, "F");

      this.doc.setFont("helvetica", "normal");
      this.doc.setFontSize(7);
      this.doc.setTextColor(...COLORS.textDim);
      this.doc.text(m.label, this.margin + 8, this.y + 11);

      const c = m.tone === "up" ? COLORS.up : m.tone === "down" ? COLORS.down : COLORS.white;
      this.doc.setFont("helvetica", "bold");
      this.doc.setTextColor(...c);
      this.doc.text(m.value, this.pageWidth - this.margin - 8, this.y + 11, { align: "right" });

      this.y += 16;
    });

    this.y += 8;
  }

  textBlock(text: string) {
    this.checkPage(30);
    this.doc.setFont("helvetica", "normal");
    this.doc.setFontSize(7);
    this.doc.setTextColor(...COLORS.textDim);
    const lines = this.doc.splitTextToSize(text, this.contentWidth - 16);
    this.doc.text(lines, this.margin + 8, this.y + 10);
    this.y += lines.length * 10 + 12;
  }

  async captureElement(element: HTMLElement, opts?: { maxHeight?: number }) {
    this.checkPage(opts?.maxHeight ?? 200);

    try {
      const canvas = await html2canvas(element, {
        backgroundColor: "#121216",
        scale: 2,
        logging: false,
        useCORS: true,
      });

      const imgData = canvas.toDataURL("image/png");
      const aspectRatio = canvas.width / canvas.height;
      const imgWidth = this.contentWidth;
      const imgHeight = Math.min(imgWidth / aspectRatio, opts?.maxHeight ?? 300);

      this.doc.addImage(imgData, "PNG", this.margin, this.y, imgWidth, imgHeight);
      this.y += imgHeight + 12;
    } catch {
      this.textBlock("[Chart capture unavailable]");
    }
  }

  spacer(h = 8) {
    this.y += h;
  }

  addFooter() {
    const pageCount = this.doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      this.doc.setPage(i);
      const pageHeight = this.doc.internal.pageSize.getHeight();

      this.doc.setDrawColor(...COLORS.border);
      this.doc.line(this.margin, pageHeight - 28, this.pageWidth - this.margin, pageHeight - 28);

      this.doc.setFont("helvetica", "normal");
      this.doc.setFontSize(6);
      this.doc.setTextColor(...COLORS.textDim);
      this.doc.text("CONFIDENTIAL — Market Terminal Report", this.margin, pageHeight - 16);
      this.doc.text(`Page ${i} of ${pageCount}`, this.pageWidth - this.margin, pageHeight - 16, { align: "right" });
    }
  }

  save(filename: string) {
    this.addFooter();
    this.doc.save(filename);
  }
}
