
import { useEffect, useRef, useState } from "react";
import { PageHeader } from "@/components/ui/PageHeader";
import { ProvenanceBadge } from "@/components/ui/ProvenanceBadge";
import { Panel, Tag } from "@/components/ui/Panel";
import { BarChart } from "@/components/charts/BarChart";
import { LineChart } from "@/components/charts/LineChart";
import { getSLSummary, getInventory } from "@/data/securitiesLending";
import { getFinancingOpportunities } from "@/data/primeFinance";
import { getCollateralSummary } from "@/data/collateral";
import { getCashSummary } from "@/data/cash";
import { fmtUsdAbbr, fmtSignedPct, fmtPct, fmtNum, fmtBps } from "@/lib/format";

interface AnswerTable {
  cols: string[];
  rows: (string | number)[][];
}
interface AnswerChart {
  type: "bar" | "line";
  data: { label: string; value: number; color?: string }[];
}
interface Answer {
  text: string;
  bullets?: string[];
  table?: AnswerTable;
  chart?: AnswerChart;
  actions?: string[];
}
interface ChatMsg {
  id: number;
  role: "user" | "assistant";
  text?: string; // raw text for user msgs
  answer?: Answer; // structured payload for assistant msgs
  source?: "AI" | "LOCAL"; // provenance of the assistant answer
}

const SUGGESTED = [
  "Why did securities lending revenue decline today?",
  "Which borrowers generated the most revenue this month?",
  "How much collateral savings were generated by today's optimization run?",
  "Show hard-to-borrow securities with utilization above 90%.",
  "Identify internalization opportunities.",
  "What is driving funding costs higher?",
];

const DATA_SOURCES = [
  "Securities Lending",
  "Prime Finance",
  "Collateral Mgmt",
  "Cash / Treasury",
  "Markets",
  "Optimization",
  "Alerts",
];

const CAPABILITIES = [
  "Query every desk dataset in natural language",
  "Explain revenue & funding-cost trends",
  "Generate charts and ranked tables on demand",
  "Surface hard-to-borrow & specials risk",
  "Find internalization & financing savings",
  "Recommend next-best actions per desk",
];

/** Deterministic local answer engine — keyword match over loaded datasets. */
function answerFor(qRaw: string): Answer {
  const q = qRaw.toLowerCase();
  const has = (...t: string[]) => t.some((x) => q.includes(x));

  // Revenue decline / drivers
  if (has("revenue") && has("declin", "drop", "down", "fell", "lower", "decrease")) {
    const sl = getSLSummary();
    const top = sl.bySecurity.slice(0, 5);
    const bottom = sl.bySecurity.slice(-3).reverse();
    return {
      text: `Securities lending revenue printed ${fmtUsdAbbr(sl.dayRevenue)} today, ${fmtSignedPct(
        sl.dayChgPct
      )} versus the prior session. The move is concentrated in a handful of names — ${top[0].label} remains the largest single contributor while the long tail of GC names softened.`,
      bullets: [
        `Day revenue ${fmtUsdAbbr(sl.dayRevenue)} (${fmtSignedPct(sl.dayChgPct)} vs prior)`,
        `Blended fee ${fmtBps(sl.avgFeeBps)} across ${fmtNum(sl.activeLoans, 0)} active loans`,
        `Top contributor ${top[0].label} at ${fmtPct(top[0].share)} of book revenue`,
        `Softest names: ${bottom.map((b) => b.label).join(", ")}`,
      ],
      chart: {
        type: "bar",
        data: top.map((s) => ({ label: s.label, value: s.dayRevenue, color: "#FF8C00" })),
      },
      actions: ["Re-rate softening specials", "Recall low-fee GC loans", "Push HTB inventory to demand"],
    };
  }

  // Top borrowers this month
  if (has("borrower") && (has("most", "top", "best", "month", "revenue", "which"))) {
    const sl = getSLSummary();
    const top = sl.byBorrower.slice(0, 8);
    return {
      text: `Top borrowers ranked by revenue contribution. The book is led by ${top[0].label}, which alone represents ${fmtPct(
        top[0].share
      )} of desk revenue.`,
      table: {
        cols: ["Borrower", "Day Rev", "Share"],
        rows: top.map((b) => [b.label, fmtUsdAbbr(b.dayRevenue), fmtPct(b.share)]),
      },
      chart: {
        type: "bar",
        data: top.slice(0, 6).map((b) => ({ label: b.label, value: b.dayRevenue, color: "#3B9DFF" })),
      },
      actions: ["Review top-3 concentration", "Upsell HTB to lead borrowers"],
    };
  }

  // Collateral savings
  if (has("collateral") && has("saving", "optimiz", "optimis")) {
    const c = getCollateralSummary();
    return {
      text: `Today's collateral optimization run generated ${fmtUsdAbbr(
        c.optimizedSavings
      )} of estimated savings by re-allocating toward cheaper-to-deliver assets.`,
      bullets: [
        `Optimized savings ${fmtUsdAbbr(c.optimizedSavings)}`,
        `Current pledge cost ${fmtUsdAbbr(c.currentCost)} → optimized ${fmtUsdAbbr(c.optimizedCost)}`,
        `Collateral utilization ${fmtPct(c.utilizationPct)}, ${c.deficitCount} margin deficits`,
      ],
      actions: ["Commit optimized allocation", "Review binding constraints"],
    };
  }

  // Hard-to-borrow util > 90
  if (has("hard-to-borrow", "hard to borrow", "htb") || (has("utilization", "util") && has("90", "above", "high"))) {
    const rows = getInventory()
      .filter((r) => (r.classification === "HTB" || r.classification === "SPECIAL") && r.utilization > 90)
      .sort((a, b) => b.utilization - a.utilization)
      .slice(0, 12);
    return {
      text: `Found ${rows.length} hard-to-borrow / special positions running above 90% utilization — these are the tightest names on the book and the best re-rate candidates.`,
      table: {
        cols: ["Ticker", "Util", "Fee", "Class"],
        rows: rows.map((r) => [r.ticker, fmtPct(r.utilization), fmtBps(r.feeBps), r.classification]),
      },
      actions: ["Re-rate to market", "Source incremental supply", "Flag recall risk"],
    };
  }

  // Internalization opportunities
  if (has("internaliz", "internalis")) {
    const opps = getFinancingOpportunities().filter((o) => o.type === "INTERNALIZE").slice(0, 10);
    const total = opps.reduce((a, o) => a + o.savings, 0);
    return {
      text: `Identified ${opps.length} internalization opportunities worth ${fmtUsdAbbr(
        total
      )} in annualized savings by matching long/short demand on-book instead of going to the street.`,
      table: {
        cols: ["Client", "Ticker", "Cur", "Opt", "Savings"],
        rows: opps.map((o) => [
          o.client,
          o.ticker,
          fmtBps(o.currentBps),
          fmtBps(o.optimizedBps),
          fmtUsdAbbr(o.savings),
        ]),
      },
      chart: {
        type: "bar",
        data: opps.slice(0, 6).map((o) => ({ label: o.ticker, value: o.savings, color: "#2ECC71" })),
      },
      actions: ["Route to internalization desk", "Confirm inventory availability"],
    };
  }

  // Funding costs
  if (has("funding", "cost of funds") && has("cost", "higher", "driving", "rising", "up")) {
    const cash = getCashSummary();
    return {
      text: `Blended funding cost is ${fmtBps(cash.blendedRateBps, 1)}, with the optimizer targeting ${fmtBps(
        cash.optimizedRateBps,
        1
      )} — a ${fmtBps(cash.savingsBps, 1)} improvement worth ${fmtUsdAbbr(
        cash.savingsUsd
      )}. Pressure is coming from term repo and FX-swap funding pricing above the operating-cash floor.`,
      bullets: [
        `Blended rate ${fmtBps(cash.blendedRateBps, 1)} vs optimized ${fmtBps(cash.optimizedRateBps, 1)}`,
        `Addressable savings ${fmtBps(cash.savingsBps, 1)} / ${fmtUsdAbbr(cash.savingsUsd)}`,
        `Funding gap ${fmtUsdAbbr(cash.fundingGap)} · LCR ${fmtPct(cash.lcr)} · NSFR ${fmtPct(cash.nsfr)}`,
      ],
      actions: ["Shift draws to cheapest source", "Term out at the front end", "Mobilize seclending cash"],
    };
  }

  // Fallback
  return {
    text: "I query all connected securities-finance datasets, explain trends, build charts, and recommend actions. Try one of these:",
    bullets: SUGGESTED,
  };
}

let MSG_ID = 100;

function AnswerView({ a }: { a: Answer }) {
  return (
    <div className="flex flex-col gap-2">
      <p className="text-2xs leading-relaxed text-term-text">{a.text}</p>

      {a.bullets && (
        <ul className="flex flex-col gap-0.5">
          {a.bullets.map((b, i) => (
            <li key={i} className="flex gap-1.5 text-2xs text-term-text-dim">
              <span className="text-term-amber">▸</span>
              <span>{b}</span>
            </li>
          ))}
        </ul>
      )}

      {a.table && (
        <div className="overflow-hidden border border-term-border">
          <table className="w-full border-collapse">
            <thead>
              <tr className="bg-term-panel-2">
                {a.table.cols.map((c, i) => (
                  <th
                    key={i}
                    className={`border-b border-term-border px-2 py-1 text-3xs font-semibold uppercase tracking-wider text-term-text-mute ${
                      i === 0 ? "text-left" : "text-right"
                    }`}
                  >
                    {c}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody className="tnum">
              {a.table.rows.map((r, ri) => (
                <tr key={ri} className="border-b border-term-border-soft hover:bg-term-panel-2">
                  {r.map((cell, ci) => (
                    <td
                      key={ci}
                      className={`px-2 py-[3px] text-2xs ${
                        ci === 0 ? "text-left text-term-text" : "text-right text-term-text-dim"
                      }`}
                    >
                      {cell}
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {a.chart && a.chart.type === "bar" && (
        <div className="border border-term-border bg-term-panel-2 p-2">
          <BarChart data={a.chart.data} horizontal fmt={(n) => fmtUsdAbbr(n)} />
        </div>
      )}
      {a.chart && a.chart.type === "line" && (
        <div className="border border-term-border bg-term-panel-2 p-2">
          <LineChart
            height={120}
            series={[{ name: "series", data: a.chart.data.map((d) => d.value), color: "#FF8C00", area: true }]}
          />
        </div>
      )}

      {a.actions && a.actions.length > 0 && (
        <div className="flex flex-col gap-1 border-t border-term-border-soft pt-1.5">
          <span className="text-3xs uppercase tracking-wider text-term-text-mute">Recommended actions</span>
          <div className="flex flex-wrap gap-1">
            {a.actions.map((act, i) => (
              <Tag key={i} tone="amber">
                {act}
              </Tag>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

export default function AICopilot() {
  const [messages, setMessages] = useState<ChatMsg[]>([
    {
      id: 1,
      role: "assistant",
      answer: {
        text: "Bloomberg GPT — Securities Finance Intelligence. I'm connected live to every desk dataset. Ask about revenue drivers, borrower rankings, hard-to-borrow risk, collateral savings, internalization, or funding costs, and I'll query the data, chart it, and recommend actions.",
        bullets: ["Pick a suggested prompt on the right, or type your own question below."],
      },
    },
  ]);
  const [input, setInput] = useState("");
  const [pending, setPending] = useState(false);
  const threadRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (threadRef.current) threadRef.current.scrollTop = threadRef.current.scrollHeight;
  }, [messages, pending]);

  const ask = async (text: string) => {
    const t = text.trim();
    if (!t || pending) return;
    setMessages((m) => [...m, { id: ++MSG_ID, role: "user", text: t }]);
    setInput("");
    setPending(true);

    // Deterministic answer is computed locally from real desk data — it supplies
    // the charts/tables/actions and is the fallback when the model is unavailable.
    const local = answerFor(t);
    try {
      const res = await fetch("/api/copilot", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ question: t }),
      });
      const j = await res.json();
      if (j?.source === "AI" && j.text) {
        // Claude narrative + the deterministic (real-data) visuals.
        const merged: Answer = {
          text: j.text,
          bullets: Array.isArray(j.bullets) && j.bullets.length ? j.bullets : undefined,
          table: local.table,
          chart: local.chart,
          actions: local.actions,
        };
        setMessages((m) => [...m, { id: ++MSG_ID, role: "assistant", answer: merged, source: "AI" }]);
      } else {
        setMessages((m) => [...m, { id: ++MSG_ID, role: "assistant", answer: local, source: "LOCAL" }]);
      }
    } catch {
      setMessages((m) => [...m, { id: ++MSG_ID, role: "assistant", answer: local, source: "LOCAL" }]);
    } finally {
      setPending(false);
    }
  };

  return (
    <div className="flex min-h-full flex-col">
      <PageHeader code="AI" title="AI Copilot" desc="Natural-language Securities Finance Intelligence" right={<ProvenanceBadge source="SIM" />} />

      <div className="grid flex-1 grid-cols-1 gap-2 p-2 xl:grid-cols-[1fr_320px]">
        {/* LEFT — chat thread + input */}
        <Panel title="Bloomberg GPT" code="CHAT" accent className="min-h-[560px]">
          <div className="flex h-full min-h-0 flex-col">
            <div ref={threadRef} className="min-h-0 flex-1 space-y-3 overflow-auto p-3">
              {messages.map((msg) =>
                msg.role === "user" ? (
                  <div key={msg.id} className="flex justify-end">
                    <div className="max-w-[78%] rounded-sm border border-term-border bg-term-panel-3 px-2.5 py-1.5 text-2xs text-term-text">
                      {msg.text}
                    </div>
                  </div>
                ) : (
                  <div key={msg.id} className="flex gap-2">
                    <span className="mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-sm border border-term-amber/50 bg-term-amber/10 text-3xs font-bold text-term-amber">
                      AI
                    </span>
                    <div className="min-w-0 max-w-[88%] rounded-sm border border-term-border bg-term-panel-2 px-2.5 py-2">
                      {msg.source && (
                        <div className="mb-1.5 flex items-center gap-1">
                          <Tag tone={msg.source === "AI" ? "up" : "amber"}>
                            {msg.source === "AI" ? "Claude · claude-opus-4-8" : "Local engine"}
                          </Tag>
                        </div>
                      )}
                      {msg.answer && <AnswerView a={msg.answer} />}
                    </div>
                  </div>
                )
              )}

              {pending && (
                <div className="flex gap-2">
                  <span className="mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-sm border border-term-amber/50 bg-term-amber/10 text-3xs font-bold text-term-amber">
                    AI
                  </span>
                  <div className="flex items-center gap-1.5 rounded-sm border border-term-border bg-term-panel-2 px-2.5 py-2 text-2xs text-term-text-dim">
                    <span className="h-1.5 w-1.5 animate-blink rounded-full bg-term-amber" />
                    analyzing datasets…
                  </div>
                </div>
              )}
            </div>

            {/* input */}
            <div className="shrink-0 border-t border-term-border bg-term-panel-2 p-2">
              <div className="flex items-center gap-2">
                <input
                  value={input}
                  onChange={(e) => setInput(e.target.value)}
                  onKeyDown={(e) => {
                    if (e.key === "Enter") ask(input);
                  }}
                  placeholder="Ask about revenue, borrowers, collateral, funding…"
                  className="tnum min-w-0 flex-1 border border-term-border bg-term-panel px-2 py-1.5 text-2xs text-term-text placeholder:text-term-text-mute focus:border-term-amber focus:outline-none"
                />
                <button onClick={() => ask(input)} disabled={pending} className="term-btn disabled:opacity-40">
                  Send
                </button>
              </div>
            </div>
          </div>
        </Panel>

        {/* RIGHT — suggested prompts + sources + capabilities */}
        <div className="flex flex-col gap-2">
          <Panel title="Suggested Prompts" code="ASK">
            <div className="flex flex-col gap-1 p-2">
              {SUGGESTED.map((s) => (
                <button
                  key={s}
                  onClick={() => ask(s)}
                  disabled={pending}
                  className="rounded-sm border border-term-border bg-term-panel-2 px-2 py-1.5 text-left text-2xs text-term-text-dim transition-colors hover:border-term-amber hover:text-term-amber disabled:opacity-40"
                >
                  {s}
                </button>
              ))}
            </div>
          </Panel>

          <Panel title="Connected Data Sources" code="FEED">
            <div className="flex flex-col divide-y divide-term-border-soft">
              {DATA_SOURCES.map((d) => (
                <div key={d} className="flex items-center justify-between px-2 py-1.5 text-2xs">
                  <span className="text-term-text-dim">{d}</span>
                  <span className="flex items-center gap-1.5 text-3xs text-term-up">
                    <span className="h-1.5 w-1.5 animate-blink rounded-full bg-term-up" />
                    LIVE
                  </span>
                </div>
              ))}
            </div>
          </Panel>

          <Panel title="Capabilities" code="WHAT">
            <ul className="flex flex-col gap-1 p-2">
              {CAPABILITIES.map((c) => (
                <li key={c} className="flex gap-1.5 text-2xs text-term-text-dim">
                  <span className="text-term-amber">▸</span>
                  <span>{c}</span>
                </li>
              ))}
            </ul>
          </Panel>
        </div>
      </div>
    </div>
  );
}
