/**
 * Vercel serverless catch-all for `/api/*`.
 *
 * Vercel's function bundler cannot resolve the app's `@/` aliases or Vite's
 * `import.meta.glob`, so this function imports the **Vite-built** handler bundle
 * (`dist-vercel/handler.js`, produced by `npm run build:vercel` before functions
 * are bundled) rather than the TypeScript source. The Node↔Web adapters come
 * from `src/server/nodeAdapter.ts`, which is alias-free and bundles directly.
 *
 * This is the same route registry the dev server and standalone server use, so
 * a Vercel deployment serves live `/api/*` data when providers are configured
 * (`FRED_API_KEY`, `MARKET_DB_URL`/`MARKET_PIPELINE_URL`, news/social keys).
 */
import type { IncomingMessage, ServerResponse } from "node:http";
import { toWebRequest, sendWebResponse, readBody } from "../src/server/nodeAdapter";
// eslint-disable-next-line import/no-unresolved -- generated by `npm run build:handler`
import { handleApiRequest } from "../dist-vercel/handler.js";

export default async function handler(req: IncomingMessage, res: ServerResponse): Promise<void> {
  try {
    const url = new URL(req.url ?? "/", `https://${req.headers.host ?? "localhost"}`);
    const method = (req.method ?? "GET").toUpperCase();
    // Only drain a body for methods that carry one, and only if the platform
    // has not already consumed the stream — avoids hanging on an ended request.
    const body =
      method !== "GET" && method !== "HEAD" && !req.readableEnded ? await readBody(req) : undefined;

    const request = toWebRequest(req, url, body);
    const response = await handleApiRequest(request);
    if (!response) {
      res.statusCode = 404;
      res.setHeader("content-type", "application/json");
      res.end(JSON.stringify({ error: "Not found" }));
      return;
    }
    await sendWebResponse(res, response);
  } catch (err) {
    res.statusCode = 500;
    res.setHeader("content-type", "application/json");
    res.end(JSON.stringify({ error: (err as Error).message ?? "internal error" }));
  }
}
